### PR TITLE
Shortcut to show the most recent request

### LINKED ISSUE #62: UI improvement - last request
It will be nice to have way to see last action, like
```
http://localhost:3001/breeze/requests/last
```
And menu for it.

Idea is ability to keep this page open next to app page, and just reload it to see result. No menu navigate to get last request, no open last request from console each time.

### PR DESCRIPTION
**Pull request by jwoertink**
Fixes #62

### CODE REVIEW

**Review by matthewmcgarvey — APPROVED** [review]

**Comment by robacarp** [comment]
Clever. I have no objection to it, but out of curiosity is it possible to declare an action which does this explicitly?

**Comment by jwoertink** [comment]
You mean have a separate action just for this? I guess we could break them in to 2 actions... They could render the same page. Then I wouldn't need any special query logic 🤔

**Comment by robacarp** [comment]
Right. I guess what I'm wondering is, does lucky know what to do if it has both `get "/requests/last"` and `get "/requests/:id"` Actions? Out of context for this pull request, perhaps.

**Comment by jwoertink** [comment]
Yeah, it could distinguish between those. I wonder if that would be a better approach? Now I'm sort of leaning towards that 😂

**Comment by jwoertink** [comment]
I was considering making this change, but after coming back to it after several months, I realized that I actually prefer this pattern.

**Pull request merged**
